name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

permissions:
  contents: read

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    name: BiomeJS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run Biome (lint)
        run: npm run lint:github

  test:
    name: Vitest
    needs: biome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      # (Optionnel) si better-sqlite3 doit se recompiler:
      # - name: Install build tools
      #   run: sudo apt-get update && sudo apt-get install -y build-essential python3

      - name: Rewrite fixtures
        run: npm run rewrites

      - name: Run tests (Vitest)
        run: npm run test

      # (Optionnel) si tu actives la couverture dans Vitest:
      # - name: Coverage report
      #   run: npm run test:cov
      #
      - name: Upload coverage artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
